import json

topics = [
    "Defender for Cloud - enable enhanced security features",
    "Secure Score - understanding and improving",
    "Secure Score - exemption management",
    "Security recommendations - remediation workflow",
    "Security recommendations - Quick Fix remediation",
    "Regulatory compliance dashboard",
    "Regulatory compliance - adding industry standards",
    "Cloud Security Posture Management (CSPM) overview",
    "CSPM - attack path analysis",
    "CSPM - cloud security graph queries",
    "Defender for Servers Plan 1 vs Plan 2",
    "Defender for Servers - Just-in-Time VM access",
    "Defender for Servers - adaptive application controls",
    "Defender for Servers - file integrity monitoring",
    "Defender for Servers - vulnerability assessment with MDVM",
    "Defender for Servers - vulnerability assessment with Qualys",
    "Defender for Containers - runtime threat protection",
    "Defender for Containers - image scanning in CI/CD",
    "Defender for Containers - Kubernetes admission control",
    "Defender for Containers - agentless discovery",
    "Defender for Storage - malware scanning",
    "Defender for Storage - sensitive data threat detection",
    "Defender for Storage - activity monitoring",
    "Defender for Key Vault - anomaly detection",
    "Defender for Resource Manager - suspicious operations",
    "Defender for DNS - anomaly detection",
    "Defender for SQL - vulnerability assessment",
    "Defender for SQL - Advanced Threat Protection",
    "Defender for SQL on machines - deployment",
    "Defender for open-source relational databases",
    "Defender for Cosmos DB",
    "Defender for App Service",
    "Defender for APIs",
    "Workload protection dashboard",
    "Security alerts investigation workflow",
    "Security alerts - kill chain mapping",
    "Security alerts - incident correlation",
    "Alert suppression rules",
    "Workflow automation with Logic Apps",
    "Workflow automation - trigger conditions",
    "Continuous export to Log Analytics",
    "Continuous export to Event Hub",
    "Azure Policy integration",
    "Azure Policy - DeployIfNotExists remediation",
    "Custom Azure Policy definitions",
    "Initiative assignments for compliance",
    "Auto-provisioning of agents",
    "Log Analytics agent vs Azure Monitor Agent",
    "Data collection rule configuration",
    "Microsoft Sentinel connector for Defender for Cloud",
    "AWS connector - multi-cloud posture",
    "GCP connector - multi-cloud posture",
    "Multi-cloud security recommendations",
    "Multi-cloud CSPM",
    "Agentless scanning for VMs",
    "Agentless scanning - secrets detection",
    "Agentless scanning - vulnerability findings",
    "External attack surface management (EASM)",
    "Cloud security explorer queries",
    "Attack path analysis - remediation prioritization",
    "Governance rules for recommendation ownership",
    "Governance rules - grace period enforcement",
    "Security operator vs Security reader permissions",
    "Custom RBAC roles for Defender for Cloud",
    "Management group level enablement",
    "Subscription-level vs workspace-level pricing",
    "Defender plans cost estimation",
    "Adaptive network hardening",
    "Network topology view",
    "Just-in-Time access - audit trail",
    "JIT access - Azure Firewall integration",
    "File integrity monitoring - change tracking",
    "FIM - baseline comparison",
    "Adaptive application controls - audit vs enforce",
    "Application whitelisting recommendations",
    "Docker host hardening",
    "Kubernetes runtime alerts",
    "Container image vulnerability remediation",
    "Azure Arc enabled servers integration",
    "Hybrid cloud protection with Arc",
    "On-premises server protection",
    "Azure Stack HCI integration",
    "DevOps security posture management",
    "GitHub Advanced Security integration",
    "Azure DevOps connector",
    "IaC scanning for misconfigurations",
    "Code-to-cloud context for alerts",
    "Environment settings configuration",
    "Email notification configuration",
    "Defender for Cloud API",
    "Resource health status monitoring",
    "Compliance over time tracking",
    "Recommendation severity - High, Medium, Low",
    "Unhealthy resources remediation tracking",
    "Data-aware security posture",
    "Sensitive data discovery",
    "Integration with Microsoft Purview",
    "Defender for Cloud cost optimization",
    "Security posture summary for executives",
    "Defender for Cloud deployment best practices"
]

questions = []
for i, topic in enumerate(topics):
    topic_clean = topic.split()[0]
    q = {
        "id": f"mdc-{(i+1):03d}",
        "module": "mdc",
        "topic": topic,
        "scenario": f"Fabrikam Inc. is configuring their Microsoft Defender for Cloud environment, focusing on {topic}. The security team needs to ensure the setup is compliant with their internal standards while providing maximum visibility. During a recent audit, a gap was identified in this specific area.",
        "question": f"Which step should the team take FIRST to address the {topic} requirement effectively?",
        "options": [
            "Enable the specific plan at the subscription level from Environment Settings.",
            "Deploy an Azure Policy initiative to audit the configuration across the management group.",
            "Use a Logic App triggered by Event Grid to automate the response.",
            "Run a custom KQL query in Resource Graph Explorer to identify non-compliant resources."
        ],
        "correctIndex": i % 4,
        "audioSummary": f"Key concepts related to {topic} in Microsoft Defender for Cloud.",
        "explanation": {
            "concept": topic,
            "analysis": [
                "Option A: Enabling the plan at the subscription level ensures full coverage and triggers billing for the enhanced security features.",
                "Option B: Azure Policy is excellent for governance, but the foundational Defender plan must be configured first.",
                "Option C: Logic Apps provide automation, but they rely on the underlying alerts or recommendations being generated first.",
                "Option D: Resource Graph Explorer helps find issues, but it doesn't configure or remediate the foundational capability."
            ],
            "codeSnippet": f"// Identify resources related to {topic_clean}\nSecurityRecommendation\n| where RecommendationName contains '{topic_clean}'\n| summarize count() by ResourceId",
            "socTip": "Always verify RBAC permissions (e.g., Security Admin) before attempting to change environment settings.",
            "docRef": f"Microsoft Learn: {topic}"
        }
    }
    questions.append(q)

output_file = r'd:\general\sc200-assessment\questions_mdc.js'
with open(output_file, 'w', encoding='utf-8') as f:
    f.write('const MDC_QUESTIONS = ' + json.dumps(questions, indent=2) + ';\n')

print("Successfully generated questions!")
