"""
SC-200 Question Merger
----------------------
1. Runs all 5 module generators (gen_*_v2.py)
2. Merges their JS outputs into a single sc200_questions.js

Modules (100 each = 500 total):
  - Copilot for Security   (copilot-001 .. copilot-100)
  - Defender for Endpoint  (mde-001 .. mde-100)
  - Defender for Cloud     (mdc-001 .. mdc-100)
  - Microsoft Purview      (purview-001 .. purview-100)
  - Defender XDR           (xdr-001 .. xdr-100)

Usage:
  python3 merge_questions.py
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent

# Generators run first (in order), then their JS outputs are merged
GENERATORS = [
    "gen_copilot_v2.py",
    "gen_mde_v2.py",
    "gen_mdc_v2.py",
    "gen_purview_v2.py",
    "gen_xdr_v2.py",
]

MODULES = [
    ("copilot", "questions_copilot_v2.js"),
    ("mde", "questions_mde_v2.js"),
    ("mdc", "questions_mdc_v2.js"),
    ("purview", "questions_purview_v2.js"),
    ("xdr", "questions_xdr_v2.js"),
]

OUTPUT_FILE = "sc200_questions.js"
EXPECTED_PER_MODULE = 100


def run_generators() -> None:
    """Execute each gen_*_v2.py so JS banks are regenerated before merge."""
    print("[*] Step 1/2 — Running module generators\n")
    for script in GENERATORS:
        path = BASE / script
        if not path.exists():
            raise SystemExit(f"[!] Missing generator: {path}")
        print(f"  → {script}")
        result = subprocess.run(
            [sys.executable, str(path)],
            cwd=str(BASE),
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(result.stdout)
            print(result.stderr, file=sys.stderr)
            raise SystemExit(f"[!] Generator failed: {script} (exit {result.returncode})")
        # Show generator summary lines
        for line in (result.stdout or "").splitlines():
            if line.strip():
                print(f"      {line}")
        print()


def load_js_array(path: Path) -> list:
    """Parse a const NAME = [...]; JS file into a Python list."""
    text = path.read_text(encoding="utf-8")
    match = re.search(r"=\s*(\[.*\])\s*;", text, re.DOTALL)
    if not match:
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1:
            raise ValueError(f"Could not find JSON array in {path}")
        raw = text[start : end + 1]
    else:
        raw = match.group(1)
    return json.loads(raw)


def validate_module(name: str, questions: list) -> None:
    """Ensure count, unique ids, and required fields."""
    if len(questions) != EXPECTED_PER_MODULE:
        raise SystemExit(
            f"[!] {name}: expected {EXPECTED_PER_MODULE} questions, got {len(questions)}"
        )
    ids = [q.get("id") for q in questions]
    if len(set(ids)) != len(ids):
        raise SystemExit(f"[!] {name}: duplicate ids found")
    for q in questions:
        q["module"] = name  # normalize
        if not q.get("id"):
            raise SystemExit(f"[!] {name}: question missing id")
        for field in ("topic", "scenario", "question", "options", "correctIndex", "explanation"):
            if field not in q:
                raise SystemExit(f"[!] {name}/{q.get('id')}: missing field '{field}'")


def merge_questions() -> None:
    """Load all module JS files and write sc200_questions.js."""
    print("[*] Step 2/2 — Merging into sc200_questions.js\n")
    merged: list = []
    summary = []

    for name, filename in MODULES:
        path = BASE / filename
        if not path.exists():
            raise SystemExit(f"[!] Missing source file after generate: {path}")
        questions = load_js_array(path)
        validate_module(name, questions)
        merged.extend(questions)
        id_range = f"{questions[0]['id']} .. {questions[-1]['id']}"
        summary.append((name, len(questions), id_range))
        print(f"  [+] {name:8s}  {len(questions):3d} questions  ({id_range})")

    total = len(merged)
    all_ids = [q["id"] for q in merged]
    if len(set(all_ids)) != total:
        raise SystemExit("[!] Duplicate ids across modules after merge")

    for i, q in enumerate(merged, start=1):
        q["globalIndex"] = i

    by_module = {name: [] for name, _ in MODULES}
    for q in merged:
        by_module[q["module"]].append(q)

    lines = [
        "/**",
        " * SC-200 Combined Question Bank",
        f" * Total: {total} questions across {len(MODULES)} modules",
        " *",
        " * Generated by merge_questions.py (runs all gen_*_v2.py first, then merges).",
        " *",
        " * Modules:",
    ]
    for name, count, id_range in summary:
        lines.append(f" *   - {name}: {count} ({id_range})")
    lines += [
        " *",
        " * Exports:",
        " *   SC200_QUESTIONS           — flat array of all questions",
        " *   SC200_QUESTIONS_BY_MODULE — { copilot, mde, mdc, purview, xdr }",
        " *   COPILOT_QUESTIONS, MDE_QUESTIONS, MDC_QUESTIONS, PURVIEW_QUESTIONS, XDR_QUESTIONS",
        " *   SC200_META                — counts and id ranges",
        " */",
        "",
        f"const SC200_QUESTIONS = {json.dumps(merged, indent=2, ensure_ascii=False)};",
        "",
        f"const SC200_QUESTIONS_BY_MODULE = {json.dumps(by_module, indent=2, ensure_ascii=False)};",
        "",
        'const COPILOT_QUESTIONS = SC200_QUESTIONS_BY_MODULE["copilot"];',
        'const MDE_QUESTIONS = SC200_QUESTIONS_BY_MODULE["mde"];',
        'const MDC_QUESTIONS = SC200_QUESTIONS_BY_MODULE["mdc"];',
        'const PURVIEW_QUESTIONS = SC200_QUESTIONS_BY_MODULE["purview"];',
        'const XDR_QUESTIONS = SC200_QUESTIONS_BY_MODULE["xdr"];',
        "",
    ]

    meta = {
        "total": total,
        "modules": {
            name: {"count": count, "idRange": id_range, "prefix": f"{name}-"}
            for name, count, id_range in summary
        },
        "order": [name for name, _ in MODULES],
    }
    lines += [
        f"const SC200_META = {json.dumps(meta, indent=2, ensure_ascii=False)};",
        "",
        "if (typeof module !== 'undefined' && module.exports) {",
        "  module.exports = {",
        "    SC200_QUESTIONS,",
        "    SC200_QUESTIONS_BY_MODULE,",
        "    COPILOT_QUESTIONS,",
        "    MDE_QUESTIONS,",
        "    MDC_QUESTIONS,",
        "    PURVIEW_QUESTIONS,",
        "    XDR_QUESTIONS,",
        "    SC200_META,",
        "  };",
        "}",
        "",
    ]

    out_path = BASE / OUTPUT_FILE
    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"\n[+] Wrote {total} questions -> {out_path.name}")
    print(f"    Unique IDs: {len(set(all_ids))}/{total}")
    print(f"    File size:  {out_path.stat().st_size:,} bytes")
    print("\n    SC200_META:")
    for name, count, id_range in summary:
        print(f"      {name:8s}  {count:3d}  {id_range}")
    print(f"      {'TOTAL':8s}  {total:3d}")


def main() -> None:
    print("=" * 60)
    print(" SC-200 merge_questions.py")
    print(" Run all generators → merge into sc200_questions.js")
    print("=" * 60 + "\n")
    run_generators()
    merge_questions()
    print("\n[✓] Done.")


if __name__ == "__main__":
    main()